### ISSUE TITLE
WSDL API script

### ISSUE THREAD

**Issue by gogleva** [ElofssonLab/TOPCONS2#1]
Hi,
I would like to use [topcons2_wsdl.py script](http://topcons.net/static/download/script/topcons2_wsdl.py) to submit jobs to the TOPCONS server inside my pipeline.
The problem is, it never seems to return an output, even when I submit a single-sequence
file. When trying to retrieve results I keep getting the status message:
```
'Your job with jobid rst_... is not ready, status = Wait'.
```
When using web server directly with the same file everything works perfectly fine. Could you please advice on what could be the issue here?

many thanks,
Anna

**Comment by nanjiangshu** [comment]
Hi Anna,

Thanks for notifying this problem. The API on the computational node for the TOPCONS2 web-server is unstable and that's why your jobs submitted via the WSDL script is hanging in the waiting list. The single-sequence jobs submitted to web-page are queued with a different mechanism that's why they are not affected. I'm looking in to this problem and will return to you when it is solved. 

Best,

Nanjiang

**Comment by arneelof** [comment]
Tack


Yours

Arne

-----------------------------------------
  Arne Elofsson                  Science for Life Laboratory
  Tel:+46-(0)70 695 1045   Stockholm University
  http://bioinfo.se/               Box 1031,
  Email: arne@bioinfo.se   17121 Solna, Sweden
  Twitter:   https://twitter.com/arneelof
  Scholar: http://scholar.google.se/citations?user=s3OCM3AAAAAJ
  ORCID: 0000-0002-7115-9751

**Comment by nanjiangshu** [comment]
Hi Anna,

The web-server should work as normal now. The problem is because "no disk space left" which is a bit strange since there was +1TB left last week. I'm digging into this problem but your problem should be solved. 

Best,

Nanjiang

**Comment by gogleva** [comment]
Hi Nanjiang,
Thanks for your quick response, everything works now. Though it takes 10-20 minutes to process one sequence. Is it normal?

Thanks for your help,
Anna

**Comment by arneelof** [comment]
This is normal, as it ends up in the back of the queue.


Yours

Arne

-----------------------------------------
  Arne Elofsson                  Science for Life Laboratory
  Tel:+46-(0)70 695 1045   Stockholm University
  http://bioinfo.se/               Box 1031,
  Email: arne@bioinfo.se   17121 Solna, Sweden
  Twitter:   https://twitter.com/arneelof
  Scholar: http://scholar.google.se/citations?user=s3OCM3AAAAAJ
  ORCID: 0000-0002-7115-9751

**Comment by gogleva** [comment]
Thanks, Arne.

**Comment by nanjiangshu** [comment]
In the file seq_0/query.result.txt (within the zipped result file) you can find the actually running time for your sequence. 

Best,

Nanjiang

**Comment by gogleva** [comment]
Thanks, Nanjiang, the actual execution time is within expected 0.7-0.9 sec range.
