### ISSUE TITLE
http://topcons.net/static/download/topcons2_database.zip  downloading link not working

### ISSUE THREAD

**Issue by DLMURPHY150** [ElofssonLab/TOPCONS2#5]
Hi TOPCONS team, I have tried downloading via the link but I get the following error message below:
"Archive:  topcons2_database.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of topcons2_database.zip or
        topcons2_database.zip.zip, and cannot find topcons2_database.zip.ZIP, period."

Even though I have this file downloaded. When I open it with archive manager the folder is empty also.
Is the download not working?

**Comment by nanjiangshu** [comment]
Hi, could you please check the md5 of you downloaded zipfile?

it should be `e87b0ded7875dced11ba90aa71a22e96`

Best,

Nanjiang

**Comment by DLMURPHY150** [comment]
No when I open it it with archive manager there are no files inside the folder whatsoever and what do you mean by md5? I am not computer science expert lol

**Comment by nanjiangshu** [comment]
md5 is a hash value unique for the file and it can be used to check the integrity of the file. That is, if two files are calculated with the same md5 value, it means these two files are identical. 

For Linux, you can use the command 
```
md5sum <file>
```
to calculate the md5 value 

and on MacOS use
```
md5 <file>
```

Could you please try to download the file again? I have just tried and it works well. The file is quite big and it may take from a few hours to a couple of days to download depending on your network speed.
