### ISSUE TITLE
not getting  "finished_seqs.txt" locally

### ISSUE THREAD

**Issue by naveen584** [ElofssonLab/TOPCONS2#8]

**Comment by naveen584** [comment]
hi,
 i am able to run topcon2 with your docker images, and as you updated it recently, it giving query_result.txt file but i am still unable to get another file that is  "finished_seqs.txt" , that we get in your web server, can you please  help.

Thanks

**Comment by nanjiangshu** [comment]
Hi @naveen584, can you describe more details about the issue?
E.g. 

which installation are you running, local host installation? docker? singularity?
what is your input data?
what is your command?
do you have the topcons2_database installed?
what is the detailed output?
what is your output folder

**Comment by nanjiangshu** [comment]
@naveen584 , the file `finished_seqs.txt` is only for the web-server as you can see from the content of the file, e.g. 

```
seq_0	250	7	False	cached	0.0	seq1	2019-11-28 14:43:38 CET
seq_1	247	7	False	newrun	30.765189	seq2	2019-11-28 14:50:28 CET
```
The content is not relevant to the actual prediction.

**Comment by lynngroup** [comment]
which installation are you running, 
 docker
what is your input data? 
search.fa
what is your command? 
 docker exec --user user topcons2 script /dev/null -c "/app/topcons2/run_topcons2.sh /scratch/search.fa -outpath  /scratch/rst_search"

do you have the topcons2_database installed?
 yes, if installation simply means, downloading the topcons2 database, then  my answer is yes.

what is the detailed output?
rst_search/
└── search
    ├── query.result.txt
    ├── query.result.txt.fa
    ├── query.result.txt.unfinished.fa
    ├── seq_0
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_1
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_10
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_11
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_12
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_13
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_14
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_15
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_16
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_17
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_18
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_19
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_2
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_20
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_21
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_22
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_23
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_24
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_25
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_26
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_27
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_28
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_29
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_3
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_4
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_5
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_6
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_7
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_8
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    ├── seq_9
    │   ├── DG1.txt
    │   ├── dg.txt
    │   ├── Homology
    │   │   ├── query.fa.total_aligns
    │   │   └── query.top
    │   ├── nicetop.html
    │   ├── OCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.prf
    │   │   └── query.top
    │   ├── philius
    │   │   └── query.top
    │   ├── PolyPhobius
    │   │   └── query.top
    │   ├── SCAMPI_MSA
    │   │   └── query.top
    │   ├── seq.fa
    │   ├── SPOCTOPUS
    │   │   ├── NN_PRF_FILES
    │   │   │   └── query.nnprf
    │   │   └── query.top
    │   └── Topcons
    │       ├── reliability.final
    │       ├── reliability.txt
    │       ├── topcons.gnu
    │       ├── topcons.large.png
    │       ├── topcons.png
    │       ├── topcons.top
    │       ├── total_image.gnu
    │       ├── total_image.large.png
    │       └── total_image.png
    └── time.txt

301 directories, 664 files

what is your output folder
i have givm tree for main folder, one more thing i have created screatch folder and put my sequence inside it, then mounted.
[topcons2_log.txt](https://github.com/ElofssonLab/TOPCONS2/files/3904875/topcons2_log.txt)

**Comment by naveen584** [comment]
@nanjiangshu Thansk for your quick support.
[topcons2_outputlog.txt](https://github.com/ElofssonLab/TOPCONS2/files/3904887/topcons2_outputlog.txt)
[topcons2_log.txt](https://github.com/ElofssonLab/TOPCONS2/files/3904888/topcons2_log.txt)
which installation are you running, 
 docker
what is your input data? 
search.fa
what is your command? 
 docker exec --user user topcons2 script /dev/null -c "/app/topcons2/run_topcons2.sh /scratch/search.fa -outpath  /scratch/rst_search"

do you have the topcons2_database installed?
 yes, if installation simply means, downloading the topcons2 database, then  my answer is yes.

what is the detailed output?
just see the above attached files.

i need that ""finished_seqs.txt"" can you please help, how i can get that file.

**Comment by nanjiangshu** [comment]
as I posted in my previous comment, the file `finished_seqs.txt` is valid only for the web-server. Why do you need this file?
